-- Pairing codes: short-lived, single-use codes for device-to-user pairing.
-- Generated by the agent during registration; claimed by the mobile user.

create table public.pairing_codes (
    id          uuid primary key default gen_random_uuid(),
    code        text not null unique,
    device_id   uuid not null references public.devices (id) on delete cascade,
    expires_at  timestamptz not null,
    claimed_by  uuid references public.profiles (id) on delete set null,
    claimed_at  timestamptz,
    created_at  timestamptz not null default now()
);

comment on table public.pairing_codes is 'Short-lived codes for device-to-user pairing (10-minute TTL)';

create index idx_pairing_codes_code on public.pairing_codes (code);
create index idx_pairing_codes_device_id on public.pairing_codes (device_id);
