-- Activity events: the core table receiving batched inserts from the agent.
-- The primary key (id) is a deterministic UUID generated by the agent,
-- enabling ON CONFLICT DO NOTHING for safe deduplication on retry.

create table public.activity_events (
    id          uuid primary key,
    device_id   uuid not null references public.devices (id) on delete cascade,
    event_type  text not null,
    severity    text not null default 'info'
                check (severity in ('info', 'low', 'medium', 'high', 'critical')),
    timestamp   timestamptz not null,
    payload     jsonb not null default '{}',
    synced_at   timestamptz not null default now()
);

comment on table public.activity_events is 'Events collected by the Windows agent';

create index idx_activity_events_device_timestamp
    on public.activity_events (device_id, timestamp desc);

create index idx_activity_events_device_type
    on public.activity_events (device_id, event_type);

create index idx_activity_events_timestamp
    on public.activity_events (timestamp desc);

create index idx_activity_events_high_severity
    on public.activity_events (device_id, timestamp desc)
    where severity in ('high', 'critical');
